#!/usr/bin/env bash

# Convenience file to activate / deactivate your conda environment.
# It must be amended (see below) and then copied to your PATH.
# Usage:
# To activate your_env:
#    source activate your_env
# To deactivate your_env:
#    conda deactivate

_CONDA_ROOT="/home/davide/anaconda/" # change to your anaconda folder
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
conda activate "$@"%     