EXAMPLE = cylinder2d
OLB_ROOT := ../../..
include $(OLB_ROOT)/default.mk

LDFLAGS 	+= -s EXPORTED_FUNCTIONS="[_runCylinder2d,_setupCylinder2d,_getNumberCellsX,_getNumberCellsY,_getValuesCells,_getCharPhysVelocity,_getPhysMaxU,_getAvgRho,_getPhysTime,_getMLUPs,_getValuesPointer,_freeMemory,_stopTimer,_startTimer,_setOutputType,_setSimulationParameters,_main]"
